### ISSUE TITLE
Update CI/e2e for OpenSourced EWC transition

### ISSUE THREAD

**Issue by armab** [StackStorm/st2ci#187]
Due to historical reasons, the CI, e2e-tests Workflows in this repo include both StackStorm OSS and EWC Enterprise logic. For example, automation spins up StackStorm OSS, e2e tests it, installs Enterprise on top of it with some migration scripts and then again e2e tests it.

As Extreme Networks open-sourced the EWC Enterprise (https://stackstorm.com/2020/05/27/extreme-networks-donates-ewc-to-linux-foundation/), we'll need to cleanup and rework all the automation and workflows to make them actual with the new fully open-source environment.

This could be one of the deep rabbit holes in the [EWC OpenSource](https://github.com/orgs/StackStorm/projects/14) plan.

**Comment by blag** [comment]
@armab Can we consider this done now that #198 is merged?

**Comment by armab** [comment]
@blag Sure! Thanks for going down that rabbit hole updating all the st2cicd workflows  :+1:
